# Generated by Django 3.0.4 on 2020-12-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MerchantRequestID', models.CharField(max_length=20)),
                ('CheckoutRequestID', models.CharField(max_length=30)),
                ('ResultCode', models.CharField(max_length=5)),
                ('Amount', models.CharField(max_length=6)),
                ('MpesaReceiptNumber', models.CharField(max_length=15)),
                ('TransactionDate', models.DateTimeField()),
                ('PhoneNumber', models.CharField(max_length=16)),
            ],
        ),
    ]
